services:
  - type: web
    name: camillo-investments-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /investments
        destination: /index.html
      - type: rewrite
        source: /auth/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_BASE_URL
        value: https://your-backend-url.onrender.com

  - type: web
    name: camillo-investments-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000 